import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import SideBar from "@/components/SideBar"
import MenuItem from "@/components/MenuItem"
import Footer from '@/components/Footer'
import Card from '@/components/Card'
import Header from '@/components/Header'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.bigbox}>
          <div>
            <div  className={styles.sidebar}>
              <SideBar/>
              <MenuItem/>
            </div>
          </div>

      
          <div className={`${styles.box2}`}>
            <Header/>
            <div className={`${styles.carditems}`}>
              <Card title="Experience" description="Studying at BCIT" borderColor="2px solid red"/>
              <Card title="Education" description="Digital Design and Development Diploma" borderColor="2px solid orange"/>
              <Card title="Project" description="Web Layout Design and Logo Design" borderColor="2px solid yellow"/>
              <Card title="Volunteering" description="none" borderColor="2px solid green"/>
              <Card title="Skills" description="Illustrator & Photoshop" borderColor="2px solid blue"/>
              <Card title="Interests" description="Cooking" borderColor="2px solid pink"/>
            </div>
          </div>
        </div>
          <div className={`${styles.footer}`}>
            <Footer/>
          </div>
      </main>
    </>
  )
}
